### ISSUE TITLE
A few Questions

### ISSUE THREAD

**Issue by beanaboston** [JanneSoon/HarshenUniverse#10]
sorry for slightly misleading title.

I'm a little suspicious since I saw a post maybe a month ago about someone who made a Harshen Universe mod on r/feedthebeast. they were banned for ban evasion, and your curse account was just made 8 days ago.

Okay wow, had to go searching for this cause the OP deleted it. Looked on ceddit, which shows posts/comments that are removed by mods, or at least says like censored in 2 seconds or something. That post does not show. Only says removed. I'm not gonna accuse you but I just find it a bit suspicious. Also it's only 18 days old so yeah, I'm a bit suspicous.

https://www.reddit.com/r/feedthebeast/comments/8yit9y/hi_i_am_a_modder_and_just_got_banned_from_curse/

OH SHIT. JUST LOOKED UP THE USERNAME OF THAT GUY, HE DELETED HIS ACCOUNT.

https://www.reddit.com/user/kenijey

more suspicion. but well, i'll let you explain yourself, i'm just suspicious cause of the whole circumstances of everything that has happened.

github account also 8 days old. also has a port of xfactors mod. i'm starting to think more and more that you're the same person. I'm not gonna report you or anything i just find this all super suspicious and want to get to the bottom of it.

**Comment by JanneSoon** [comment]
I'm not him.

**Comment by kenijey** [comment]
yea he is not me. but i knew things like this gonna happen. not surprised xD he's just my friend that we live in same place. we're students that learning java and  i just recommended him held my project and continue develop it so it will worth it. since i understood that my ban will never be removed on curse, i dont really think i will mod anymore. it already got boring..
